eureka:
  client:
    service-url:
      defaultZone: http://192.168.59.103:1111/eureka/

logging:
  file: application.log
  level:
      org:
        springframework:
                      aop:
                        interceptor:
                             JamonPerformanceMonitorInterceptor: TRACE 